/* Allegro datafile object indexes, produced by grabber v4.4.2, Unix */
/* Datafile: /home/tstoeter/Private/Code/stoeter-paciana/trunk/lost_.dat */
/* Date: Wed Jun 27 19:47:24 2018 */
/* Do not hand edit! */

#define LOGO                             0        /* BMP  */
#define MENU                             1        /* BMP  */
#define FONT                             2        /* BMP  */
#define TEX_PLAYGAME                     3        /* BMP  */
#define TEX_PLAYMAP                      4        /* BMP  */
#define TEX_EXIT                         5        /* BMP  */
#define TEX_SETUP                        6        /* BMP  */
#define NEXT_LEVEL                       7        /* BMP  */
#define GAME_OVER                        8        /* BMP  */
#define GAME_COMPLETE                    9        /* BMP  */
#define TILE1                            10       /* RLE  */
#define TILE2                            11       /* RLE  */
#define TILE3                            12       /* RLE  */
#define TILE4                            13       /* RLE  */
#define DOOR                             14       /* RLE  */
#define KEY                              15       /* RLE  */
#define STONE                            16       /* RLE  */
#define DYNAMITE                         17       /* RLE  */
#define MUMMY_FRONT                      18       /* RLE  */
#define MUMMY_LEFT                       19       /* RLE  */
#define MUMMY_RIGHT                      20       /* RLE  */
#define MUMMY_BACK                       21       /* RLE  */
#define PACIANA_FRONT                    22       /* RLE  */
#define PACIANA_LEFT                     23       /* RLE  */
#define PACIANA_RIGHT                    24       /* RLE  */
#define PACIANA_BACK                     25       /* RLE  */
#define SCARAB1                          26       /* BMP  */
#define SCARAB2                          27       /* BMP  */
#define SCARAB3                          28       /* BMP  */
#define SCARAB4                          29       /* BMP  */
#define TILE5                            30       /* RLE  */
#define TILE6                            31       /* RLE  */
#define TILE7                            32       /* RLE  */
#define TILE8                            33       /* RLE  */
#define TILE9                            34       /* RLE  */
#define TILE10                           35       /* RLE  */
#define FLARE                            36       /* BMP  */
#define LEVEL1                           37       /* MAP  */
#define LEVEL2                           38       /* MAP  */
#define LEVEL3                           39       /* MAP  */
#define LEVEL4                           40       /* MAP  */
#define LEVEL5                           41       /* MAP  */
#define LEVEL6                           42       /* MAP  */
#define LEVEL7                           43       /* MAP  */
#define LEVEL8                           44       /* MAP  */
#define LEVEL9                           45       /* MAP  */
#define LEVEL10                          46       /* MAP  */
#define ARROW_RIGHT                      47       /* BMP  */
#define ARROW_LEFT                       48       /* BMP  */
#define STONE3_SPL                       49       /* SAMP */
#define PYRAMID_ENTER                    50       /* SAMP */
#define SPEAKER                          51       /* BMP  */
#define SPEAKER_OFF                      52       /* BMP  */
#define FIRE_CRACKLE                     53       /* SAMP */
#define SPARKLE                          54       /* BMP  */
#define FIRESPOT                         55       /* BMP  */
#define DUSTSPOT                         56       /* BMP  */
#define DYNAMITE_ACTIVE                  57       /* RLE  */
#define JINGLE                           58       /* SAMP */
#define EXPLOSION_SPL                    59       /* SAMP */
#define GRUNT_SPL                        60       /* SAMP */
#define KEYS_SPL                         61       /* SAMP */
#define PAIN_SPL                         62       /* SAMP */
#define PICKUP_SPL                       63       /* SAMP */
#define SQUISH_SPL                       64       /* SAMP */
#define WHIP_SPL                         65       /* SAMP */
#define FUSE_SPL                         66       /* SAMP */
#define GAME_START                       67       /* BMP  */
#define NCEN                             68       /* FONT */
#define GHOST_SPL                        69       /* SAMP */
#define LOCKED_SPL                       70       /* SAMP */
#define UNLOCK_SPL                       71       /* SAMP */

